# Generated by Django 4.1 on 2022-08-17 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Training_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpe',
            options={'verbose_name': 'Rpe', 'verbose_name_plural': 'Rpes'},
        ),
        migrations.AlterModelOptions(
            name='training_session',
            options={'verbose_name': 'Sesion de Entrenamiento', 'verbose_name_plural': 'Sesiones de Entrenamiento'},
        ),
        migrations.AlterField(
            model_name='training_session',
            name='rpe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Training_sessions.rpe'),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='tr_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Training_sessions.training_type'),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
