# Generated by Django 4.1 on 2022-08-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EASTeam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='Settings',
        ),
    ]
