# Generated by Django 4.1 on 2022-08-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EASTeam', '0002_rename_about_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
    ]
